/**
 * Builds the categories-array and categories-tree files
 */

import * as path from 'path';
import * as fs from 'fs';

import { Converter } from './Converter';


const categoriesTree = require('../categories-tree.json');

Converter.writeToPath(path.resolve(__dirname, '..'));

// write the CATEGORIES.md file
let str = `
# Categories

This is an autogenerated file with all the categories in Open Categories
`;

for (const key in categoriesTree) {
  if (categoriesTree[key].topmost) {
    str += `## ${key}\n`;
  }

  str += `* ${key}\n`;
}

fs.writeFileSync(
  path.resolve(__dirname, '..', 'CATEGORIES.md'), 
  str, 
  { encoding: 'utf8' },
);
